### ISSUE TITLE
Querying multiple images with gatsby-image

### ISSUE THREAD

**Issue by AndyClifton** [octue/planex-site#25]
PR #24 provides a framework for using gatsby-image in the components in planex-site. 

## Problem
However, this is a **brute-force solution**; each image is named and referenced individually, e.g.,

```javascript 
query {
      defaultPanel: file(
        relativePath: { eq: "stock/people-in-classy-office.jpeg" }
      ) {
        childImageSharp {
          fluid(quality: 90, maxWidth: 1920) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
      topLeftPanel: file(
        relativePath: { eq: "stock/people-in-classy-office.jpeg" }
      ) {
        childImageSharp {
          fluid(quality: 90, maxWidth: 1920) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
...
```

## Affects
This can be found in the following files...
- [ ] /src/components/shuffle/BuildWithTwined/BuildWithTwined.jsx
- [ ] /src/components/shuffle/HereToHelp/HereToHelp.jsx
- [ ] /src/components/shuffle/OurMission/OurMission.jsx
- [ ] /src/components/shuffle/TakeWorkFurther/TakeWorkFurther.jsx
- [ ] /src/components/shuffle/TheTeam/TheTeam.jsx

## Solution
A potential solution is outlined in [this stackoverflow question](https://stackoverflow.com/questions/56437205/how-do-i-query-multiple-images-with-gatsby-image)

**Comment by thclark** [comment]
We're now using a later version of gatsby image, plus we've discovered that page queries, rather than static queries, are less limited so we can query for a lot at once; so will close this down as 'didn't solve but moved past'
